
# languages.py

LANGUAGES = {
    "Español": {
        "window_title": "Redescubre - Escáner de Red",
        "file_menu": "Archivo",
        "file_menu_exit": "Salir",
        "config_menu": "Configuración",
        "config_menu_lang": "Idioma",
        "help_menu": "Ayuda",
        "help_menu_about": "Acerca de...",
        "ip_range_label": "Rango de IP:",
        "ip_range_placeholder": "Ej: 192.168.0.1-100, 192.168.10.0/24, 192.168.0.200",
        "snmp_label": "SNMP:",
        "scan_button": "Escanear Red",
        "scan_button_scanning": "Escaneando...",
        "cancel_button": "Cancelar",
        "search_label": "Buscar:",
        "search_placeholder": "Filtrar (ej: online, pc-01, 192.168...)",
        "col_estado": "Estado",
        "col_ip": "IP",
        "col_hostname": "Hostname",
        "col_mac": "MAC",
        "col_manufacturer": "Fabricante",
        "col_visto_por_última_vez": "Visto por última vez",
        "ctx_ping": "Hacer Ping",
        "ctx_rdp": "Conectar por RDP",
        "ctx_http": "Abrir en Navegador (HTTP)",
        "status_initializing": "Inicializando, por favor espere...",
        "status_ready": "Listo para escanear.",
        "status_history_loaded": "Historial cargado. {} dispositivos conocidos.",
        "status_history_new": "No se encontró historial. Se creará uno nuevo.",
        "status_history_error": "Error al cargar el historial: {}",
        "status_history_save_error": "Error al guardar el historial: {}",
        "status_scanning": "Iniciando escaneo...",
        "status_cancelling": "Cancelando escaneo...",
        "status_scan_cancelled": "Escaneo cancelado por el usuario.",
        "status_scan_completed": "Escaneo completado. Se encontraron {} dispositivos.",
        "status_error_no_range": "Error: El rango de IP no puede estar vacío.",
        "status_error_scan": "Error durante el escaneo: {}",
        "export_button": "Exportar a CSV",
        "export_status_no_results": "No hay resultados para exportar.",
        "export_status_cancelled": "Exportación cancelada.",
        "export_status_success": "Resultados exportados a {}",
        "export_dialog_title": "Guardar resultados como CSV",
        "portscan_window_title": "Escaneando {}",
        "portscan_window_label": "Escaneando puertos comunes en {}...",
        "portscan_results_title": "Puertos Abiertos en {}",
        "portscan_results_label": "Puertos abiertos encontrados en {}:",
        "portscan_results_no_ports": "No se encontraron puertos abiertos.",
        "about_title": "Acerca de Redescubre",
        "about_version": "Versión 1.0",
        "about_description": ("Una herramienta de escaneo de red de código abierto, diseñada para ser\n"
                              "rápida, intuitiva y moderna. Permite descubrir dispositivos en redes\n"
                              "locales y WAN, identificar fabricantes y escanear puertos abiertos."),
        "about_author": "Desarrollado por: Milton Salcedo Cruz sistsalcedo@gmail.com",
        "about_license": "Licencia: Open Source (MIT)",
        "close_button": "Cerrar",
    },
    "Inglés": {
        "window_title": "Redescubre - Network Scanner",
        "file_menu": "File",
        "file_menu_exit": "Exit",
        "config_menu": "Settings",
        "config_menu_lang": "Language",
        "help_menu": "Help",
        "help_menu_about": "About...",
        "ip_range_label": "IP Range:",
        "ip_range_placeholder": "Ex: 192.168.0.1-100, 192.168.10.0/24, 192.168.0.200",
        "snmp_label": "SNMP:",
        "scan_button": "Scan Network",
        "scan_button_scanning": "Scanning...",
        "cancel_button": "Cancel",
        "search_label": "Search:",
        "search_placeholder": "Filter (e.g., online, server-01, 192.168...)",
        "col_estado": "Status",
        "col_ip": "IP",
        "col_hostname": "Hostname",
        "col_mac": "MAC",
        "col_manufacturer": "Manufacturer",
        "col_visto_por_última_vez": "Last Seen",
        "ctx_ping": "Ping Device",
        "ctx_rdp": "Connect with RDP",
        "ctx_http": "Open in Browser (HTTP)",
        "status_initializing": "Initializing, please wait...",
        "status_ready": "Ready to scan.",
        "status_history_loaded": "History loaded. {} known devices.",
        "status_history_new": "No history found. A new one will be created.",
        "status_history_error": "Error loading history: {}",
        "status_history_save_error": "Error saving history: {}",
        "status_scanning": "Starting scan...",
        "status_cancelling": "Cancelling scan...",
        "status_scan_cancelled": "Scan cancelled by user.",
        "status_scan_completed": "Scan completed. Found {} devices.",
        "status_error_no_range": "Error: IP range cannot be empty.",
        "status_error_scan": "Error during scan: {}",
        "export_button": "Export to CSV",
        "export_status_no_results": "No results to export.",
        "export_status_cancelled": "Export cancelled.",
        "export_status_success": "Results exported to {}",
        "export_dialog_title": "Save results as CSV",
        "portscan_window_title": "Scanning {}",
        "portscan_window_label": "Scanning common ports on {}...",
        "portscan_results_title": "Open Ports on {}",
        "portscan_results_label": "Open ports found on {}:",
        "portscan_results_no_ports": "No open ports found.",
        "about_title": "About Redescubre",
        "about_version": "Version 1.0",
        "about_description": ("An open-source network scanning tool, designed to be fast,\n"
                              "intuitive, and modern. It allows discovering devices on local\n"
                              "and WAN networks, identifying manufacturers, and scanning open ports."),
        "about_author": "Developed by: Milton Salcedo Cruz sistsalcedo@gmail.com",
        "about_license": "License: Open Source (MIT)",
        "close_button": "Close",
    }
    # Puedes añadir "Portugués" y "Chino" aquí más tarde.
}
